/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.canvasbeeapp;

/**
 *
 * @author lucim
 */
public class Senac extends javax.swing.JFrame {

    /**
     * Creates new form Senac
     */
    public Senac() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSaber = new javax.swing.JButton();
        btnInterdisciplinar = new javax.swing.JButton();
        btnNucInovacao = new javax.swing.JButton();
        btnColaboracao = new javax.swing.JButton();
        btnConquistas = new javax.swing.JButton();
        lblAluno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\lucim\\OneDrive\\Documentos\\NetBeansProjects\\CanvasBeeApp\\src\\main\\java\\com\\mycompany\\canvasbeeapp\\abelha-64px.png")); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jornada Interativa de  Aprendizagem");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Clique na letra da fase que deseja realizar");

        btnSaber.setBackground(new java.awt.Color(0, 0, 153));
        btnSaber.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSaber.setForeground(new java.awt.Color(255, 255, 255));
        btnSaber.setText("S");
        btnSaber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaberActionPerformed(evt);
            }
        });

        btnInterdisciplinar.setBackground(new java.awt.Color(0, 0, 153));
        btnInterdisciplinar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnInterdisciplinar.setForeground(new java.awt.Color(255, 255, 255));
        btnInterdisciplinar.setText("E");
        btnInterdisciplinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterdisciplinarActionPerformed(evt);
            }
        });

        btnNucInovacao.setBackground(new java.awt.Color(0, 0, 153));
        btnNucInovacao.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnNucInovacao.setForeground(new java.awt.Color(255, 255, 255));
        btnNucInovacao.setText("N");
        btnNucInovacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNucInovacaoActionPerformed(evt);
            }
        });

        btnColaboracao.setBackground(new java.awt.Color(0, 0, 153));
        btnColaboracao.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnColaboracao.setForeground(new java.awt.Color(255, 255, 255));
        btnColaboracao.setText("A");
        btnColaboracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColaboracaoActionPerformed(evt);
            }
        });

        btnConquistas.setBackground(new java.awt.Color(0, 0, 153));
        btnConquistas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnConquistas.setForeground(new java.awt.Color(255, 255, 255));
        btnConquistas.setText("C");
        btnConquistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConquistasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSaber)
                        .addGap(18, 18, 18)
                        .addComponent(btnInterdisciplinar)
                        .addGap(18, 18, 18)
                        .addComponent(btnNucInovacao)
                        .addGap(18, 18, 18)
                        .addComponent(btnColaboracao)
                        .addGap(18, 18, 18)
                        .addComponent(btnConquistas)
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lblAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaber)
                    .addComponent(btnInterdisciplinar)
                    .addComponent(btnNucInovacao)
                    .addComponent(btnColaboracao)
                    .addComponent(btnConquistas))
                .addGap(0, 258, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInterdisciplinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterdisciplinarActionPerformed
        new InterdisciplinarE().setVisible(true);
        
    }//GEN-LAST:event_btnInterdisciplinarActionPerformed

    private void btnColaboracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColaboracaoActionPerformed
        new Colaboracao().setVisible(true);
        
    }//GEN-LAST:event_btnColaboracaoActionPerformed

    private void btnSaberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaberActionPerformed
        new SaberA().setVisible(true);
               //dispose();
    }//GEN-LAST:event_btnSaberActionPerformed

    private void btnConquistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConquistasActionPerformed
        new Conquistas().setVisible(true);
        
    }//GEN-LAST:event_btnConquistasActionPerformed

    private void btnNucInovacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNucInovacaoActionPerformed
        new NucInovacao().setVisible(true);
        
    }//GEN-LAST:event_btnNucInovacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Senac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Senac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Senac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Senac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Senac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColaboracao;
    private javax.swing.JButton btnConquistas;
    private javax.swing.JButton btnInterdisciplinar;
    private javax.swing.JButton btnNucInovacao;
    private javax.swing.JButton btnSaber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAluno;
    // End of variables declaration//GEN-END:variables
}
